### ISSUE TITLE
Split r container?

### ISSUE THREAD

**Issue by eduard93** [grongierisc/iris-r-gateway-template#1]
@grongierisc what do you about splitting r into 2 containers:

- rserve container https://github.com/stevenpollack/docker-rserve
- JGW container <- JRE based

**Comment by eduard93** [comment]
Current build time for me `[+] Building 1053.8s (12/12) FINISHED`

I think this change would considerable lower build time and possibly space used (due to the lack of compilation/installation etc).

**Comment by grongierisc** [comment]
I was not able to split Rserve and the JG because of "com.intersystems.rgateway.Helper".
This helper seems to be only capable to connect to localhost Rserver.

If you manage to make it work a PR is welcome.

**Comment by eduard93** [comment]
Separated containers, please check PR.

**Comment by grongierisc** [comment]
Thx
